### ISSUE TITLE
a suggestion for blog

### ISSUE THREAD

**Issue by taojintianxia** [tristaZero/tristaZero.github.io#1]
You could create your github.io from a [template](https://github.com/topics/blog-template) , and then put the post or image in corresponding folder.

seems that kimm has github blog EXP

**Comment by tristaZero** [comment]
@taojintianxia Hi thanks for your issue!

Sorry to reply late, since I think no one will give any attention to my blog repo.
I chose [minimal](https://github.com/pages-themes/minimal) as my blog theme supported by GitHub by default. I do not need to care about Jekyll's deployment and just write markdown, which made work easy, but not my favored blog style, yep, not so beautiful.
Do you have any other ideas? Currently, my blog looks like [this](https://tristazero.github.io).

**Comment by taojintianxia** [comment]
You can find a lot of templates on github. Just fork a template to take a look on it's tructure, and then create a corresponding repo to establish your own blog . 

For example, `https://github.com/mzlogin/mzlogin.github.io`, copy the structure from that repo , put your markdown files in _posts, and then push it to your own repo.

No need to worry about the deployment ,github will handle that. 

And I hope ss team could set up a tech blog, the whole team commit tech blog to that repo, such as design patten, usage of middleware, your understanding of xx, how do you learn/desgin/test xxx. this tech resource pool not only to build influence in this business , but also for new contributor to learn the related tech .

**Comment by felixluo-dev** [comment]
@taojintianxia  A good suggestion.I have the same hope, ss team could set up a tech blog.

> You can find a lot of templates on github. Just fork a template to take a look on it's tructure, and then create a corresponding repo to establish your own blog .
> 
> For example, `https://github.com/mzlogin/mzlogin.github.io`, copy the structure from that repo , put your markdown files in _posts, and then push it to your own repo.
> 
> No need to worry about the deployment ,github will handle that.
> 
> And I hope ss team could set up a tech blog, the whole team commit tech blog to that repo, such as design patten, usage of middleware, your understanding of xx, how do you learn/desgin/test xxx. this tech resource pool not only to build influence in this business , but also for new contributor to learn the related tech .

**Comment by tristaZero** [comment]
Thanks, @AAluoxiang
At present, we have many of tech articles. I am not sure [it](https://github.com/apache/shardingsphere/issues/650) is what you want.

**Comment by felixluo-dev** [comment]
Thank you. I will read the article. @tristaZero
